apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
  namespace: default
type: Opaque
data:
  username: dXNlcg==        # 'user'   -> base64('user')
  password: dXNlcjEyMzQ=    # 'user1234' -> base64('user1234')

